package cdss.myproject;
import cdss.Symptom;
import cdss.VitalSign;
import cdss.PatientRecord;
import cdss.Diagnosis;

rule"Reinserting patient symptoms into the wm"
ruleflow-group"Diagnosis"
salience 5
no-loop true
when
patient: cdss.PatientRecord( syl:symptoms)
sy:cdss.Symptom( )from syl
then
insertLogical(sy);
System.out.println("insert fact:"+ sy.getDescription());
end

rule"inserting again patient vital signs into the wm"
ruleflow-group"Diagnosis"
salience 5
no-loop true
when
patient: cdss.PatientRecord( vsl:vitalSigns)
vs:cdss.VitalSign( )from vsl
then
insertLogical(vs);
System.out.println("insert fact:"+ vs.getName());
end


