package cdss.myproject;
import cdss.PatientRecord;
import cdss.MedicalExamination;
import cdss.Assignement;


rule"Clinical examinations"
ruleflow-group"ClinicalExamsRules"
no-loop true

when
triage:cdss.Assignement(service=="Endocrinology and diabetology" )
medicalExam: cdss.MedicalExamination( this!=null)
then
medicalExam.setName("Diabetic examination");
System.out.println( medicalExam.getName() + "is required");
end

