package cdss.myproject;
import cdss.Symptom;
import cdss.VitalSign;
import cdss.PatientRecord;
import cdss.Assignement;

rule"inserting patient symptoms into the wm"
ruleflow-group"NurseExaminations"
salience 4
no-loop true
when
patient: cdss.PatientRecord( syl:symptoms)
sy:cdss.Symptom( )from syl
then
insertLogical(sy);
System.out.println("insert fact:"+ sy.getDescription());
end

rule"inserting patient vital signs into the wm"
ruleflow-group"NurseExaminations"
salience 4
no-loop true
when
patient: cdss.PatientRecord( vsl:vitalSigns)
vs:cdss.VitalSign( )from vsl
then
insertLogical(vs);
System.out.println("insert fact:"+ vs.getName());
end

rule"Nurse tests"
ruleflow-group"NurseExaminations"
salience 4
no-loop true
when
syp1:cdss.Symptom(description=="vomiting" )
syp2: cdss.Symptom(description=="loss of consciousness" )
syp3: cdss.Symptom(description=="abdominal pain")
measurement: cdss.VitalParameterMeasurement( this!=null)
then
measurement.setName("Blood glucose test");
System.out.println(measurement.getName()+ "is required");
end

rule"Reinserting patient vital signs inton the WM"
ruleflow-group"TriageRules"
salience 3
no-loop true
when
patient: cdss.PatientRecord( vsl:vitalSigns)
vs:cdss.VitalSign( )from vsl
then
insertLogical(vs);
System.out.println("insert fact:"+ vs.getName());
end

rule"TriagePatient"
ruleflow-group"TriageRules"
salience 2
when 
vs: cdss.VitalSign( name=="Blood glucose" && value>=11)
triage:cdss.Assignement(this!=null)
then
triage.setService("Endocrinology and diabetology");
System.out.println("Suggested patient transfer:"+triage.getService());
end





