package cdss.myproject;
import cdss.PatientRecord;
import cdss.MedicalExamination;
import cdss.Assignement;


rule"Clinical examinations"
ruleflow-group"ClinicalExamsRules"
no-loop true
salience 3
when
patient: cdss.PatientRecord(Assignement.service=="Endocrinology and diabetology" )
exam: cdss.MedicalExamination(this==null)
then
exam.setName(" Diabetic examination");
System.out.println(exam.getName());

end

