package cdss.myproject;
import cdss.PatientRecord;
import cdss.VitalSign;
import cdss.Assignement;

rule"Reinserting patient vital signs inton the WM"
ruleflow-group"TriageRules"
salience 3
no-loop true
when
patient: cdss.PatientRecord( vsl:vitalSigns)
vs:cdss.VitalSign( )from vsl
then
insertLogical(vs);
System.out.println("insert fact:"+ vs.getName());
end

rule"TriagePatient"
ruleflow-group"TriageRules"
salience 2
when 
vs: cdss.VitalSign( name=="Blood glucose" && value>=11)
triage:cdss.Assignement(this!=null)
then
triage.setService("Endocrinology and diabetology");
System.out.println("Suggested patient transfer:"+triage.getService());
end




