package cdss;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Assignement")
public class Assignement implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Date")
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date date;

    @org.kie.api.definition.type.Label(value = "Service")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String service;

    @org.kie.api.definition.type.Label(value = "Urgency")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer urgency;

    public Assignement() {
    }
    
    public Assignement(java.lang.String service, java.lang.Integer urgency, java.util.Date date) {
        this.service = service;
        this.urgency = urgency;
        this.date = date;
    }

    public java.util.Date getDate() {
        return this.date;
    }
    
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public java.lang.String getService() {
        return this.service;
    }
    
    public void setService(java.lang.String service) {
        this.service = service;
    }

    public java.lang.Integer getUrgency() {
        return this.urgency;
    }
    
    public void setUrgency(java.lang.Integer urgency) {
        this.urgency = urgency;
    }

}