package cdss;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Diagnosis")
public class Diagnosis implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Date")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String date;

    @org.kie.api.definition.type.Label(value = "Value")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String value;

    public Diagnosis() {
    }
    
    public Diagnosis(java.lang.String value, java.lang.String date) {
        this.value = value;
        this.date = date;
    }

    public java.lang.String getDate() {
        return this.date;
    }
    
    public void setDate(java.lang.String date) {
        this.date = date;
    }

    public java.lang.String getValue() {
        return this.value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }

}